### PR TITLE
feat(build/spdk): bump to v24.09

### PR DESCRIPTION
**Pull request by karlowich**
This allows us to drop our out-of-tree patches.
I decided to drop everything related to the patches as a way of signifying that we shouldn't be adding new patches, and instead upstream any changes we need.

### CODE REVIEW

**Review by safl — CHANGES_REQUESTED** [review]
Excellent with the version-bump and removal of patches that are now available upstream.

The infrastructure for applying out-of-tree patches to the custom SPDK version that xNVMe builds is very convenient, let's keep that.

**Comment by karlowich** [comment]
I see your point, I will keep the patch scaffolding for ease of development in case we need to test potential changes in the future

**Review by safl — APPROVED** [review]
lgtm

**Review by NaddiNadja — APPROVED** [review]
lgtm :)

**Pull request merged**
