### PR TITLE
Creating Compute interface and adding the Hermes backend

### PR DESCRIPTION
**Pull request by niclashedam**
As agreed, here is my first iteration of the compute interface as well as the Hermes backend.
I've not had a chance to test it yet, as I have problems with the QEMU Hermes image, but I'll look into it when I have more time.

Until then, please let me know if something is not as expected.

### CODE REVIEW

**Comment by safl** [comment]
Hi @niclashedam,
It looks good! A couple of questions/notes follow

- I changed the merge-target to the ``compute`` branch as there is a bit of work before including it in ``master``
- Are the definitions in ``include/xnvme_hermes.h`` available in upstream Linux?
- With regards to testing, then a docker-container with the custom-qemu would be a way to get things rolling. It can be plugged into the infra. similar to: https://github.com/refenv/actions which produces a docker-image for xNVMe testing using upstream qemu 6.0
- Documentation in some form would be great, e.g. ``docs/backends/compute.rst`` describing requirements

Just a quick couple of thoughts as I am AFK until July 19th.

**Comment by niclashedam** [comment]
Syncing this PR to newest xNVME commit.

**Comment by niclashedam** [comment]
Any news on this and the plan going forward?

**Comment by safl** [comment]
Closing this as per offline discussion.

**Pull request closed without merging**
