### PR TITLE
Release candidate: v0.6.0

### PR DESCRIPTION
**Pull request by safl**
Boiler-plate for the release of v0.6.0 addressing the following:

* https://github.com/OpenMPDK/xNVMe/issues/167

### CODE REVIEW

**Review by karlowich — CHANGES_REQUESTED** [review]
This looks good, but the man-pages are not correctly generated, this needs to be fixed in `xnvmec_generator.py`

**Comment by karlowich** [comment]
The following needs to be done before release:

- [ ] Merge #193
- [ ] (Re-)Generate the man-pages

**Comment by safl** [comment]
> This looks good, but the man-pages are not correctly generated, this needs to be fixed in `xnvmec_generator.py`

done. thanks!

**Review by karlowich — APPROVED** [review]
Approved!

**Review by Baekalfen — APPROVED** [review]

**Pull request merged**
