### PR TITLE
add xnvme ctrl get registers

### PR DESCRIPTION
**Pull request by hmi-jeon**
add xnvme ctrl get registers

1. feat: add xnvme_ctrlr_get_registers to read controller registers
2. be:spdk: add function to get controller registeres
3. be:linux: add function to get controller registeres

### CODE REVIEW

**Comment by hmi-jeon** [comment]
@karlowich 
Hi,
I ran pre-commit and fixed the failure in source-format-check.

Thank you.

**Comment by karlowich** [comment]
@hmi-jeon Awesome! Thanks!

**Comment by hmi-jeon** [comment]
@karlowich 
A fail occurred in windows build.
Is there any way to find out the cause of this?
If there is no way, I will try to find it.
Even when I look at the workflow, I can only see the phrase Error.
Thank you.

**Comment by karlowich** [comment]
@hmi-jeon We are experiencing some problems with GitHub, maybe we need to update our runners.
@safl Can you look into this?

**Comment by karlowich** [comment]
@hmi-jeon This is your error:

```FAILED: lib/libxnvme.dll 
"gcc" @lib/libxnvme.dll.rsp
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libxnvme.dll.p/xnvme_be_spdk_dev.c.obj:xnvme_be_spdk_dev.c:(.text+0xa2): undefined reference to `spdk_nvme_ctrlr_get_registers'

collect2.exe: error: ld returned 1 exit status```

Probably this is because your out of tree spdk patch also needs to be placed inside `xnvme/subprojects/packagefiles/spdk-win/patches`.

**Comment by hmi-jeon** [comment]
@karlowich 
Hi.
I added spdk_nvme_ctrl_get_registers patch file inside spdk-win.
Thank you for checking.

**Comment by karlowich** [comment]
@hmi-jeon We got a new error:
```
nvme_pcie.c:1141:3: error: â€˜const struct spdk_nvme_transport_opsâ€™ has no member named â€˜ctrlr_get_registersâ€™; did you mean â€˜ctrlr_get_reg_4â€™?
 1141 |  .ctrlr_get_registers = nvme_pcie_ctrlr_get_registers,
      |   ^~~~~~~~~~~~~~~~~~~
      |   ctrlr_get_reg_4
nvme_pcie.c:1141:25: warning: initialization of â€˜int (*)(struct spdk_nvme_ctrlr *, uint32_t,  uint32_t)â€™ {aka â€˜int (*)(struct spdk_nvme_ctrlr *, unsigned int,  unsigned int)â€™} from incompatible pointer type â€˜volatile struct spdk_nvme_registers * (*)(struct spdk_nvme_ctrlr *)â€™ [-Wincompatible-pointer-types]
 1141 |  .ctrlr_get_registers = nvme_pcie_ctrlr_get_registers,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
nvme_pcie.c:1141:25: note: (near initialization for â€˜pcie_ops.ctrlr_set_reg_4â€™)
nvme_pcie.c:1142:21: warning: initialized field overwritten [-Woverride-init]
 1142 |  .ctrlr_set_reg_4 = nvme_pcie_ctrlr_set_reg_4,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~
nvme_pcie.c:1142:21: note: (near initialization for â€˜pcie_ops.ctrlr_set_reg_4â€™)
```

It looks a little funky, but I think it is due to the fact that on windows we use SPDK 22.05, which might lack some prerequisite for the patch

**Comment by hmi-jeon** [comment]
@karlowich 
Hi,
as you said,
Because the source is different from spdk v22.09, it was not included in the structure due to a conflict when applying the patch.
So I applied the patch file again.
Thank you for helping.

**Comment by karlowich** [comment]
@hmi-jeon Awesome! Great work!

**Review by safl — CHANGES_REQUESTED** [review]
Hi @hmi-jeon  and @sc108-lee !

Thanks a lot for this functional change; it is just what is needed, and it is excellent that support is there for Linux/mmap and via the SPDK/Driver! Really, great. However, regarding the implementation, two things are currently happening on the xNVMe code-base:

- SPDK 23.09 is out, and we want to update the xNVMe subproject to this version. When doing so, you do not have to apply the patches as they are readily available. Except for the "spdk-win" subproject, which still needs them.

- Previously, then the addition of  ``*_be_ctrlr_get_registers()`` in the backend-interface would be the recommended approach. However, we are adding a new "pseudo-command" infrastructure to handle this class of functionality without changing the backend interface.

This works by the "frontend" constructing "pseudo-commands", such as done here:

- https://github.com/OpenMPDK/xNVMe/blob/next/lib/xnvme_topology.c

These use "vendor-specific-admin-command-set" with custom command-opcodes, defined in an internal header here:

- https://github.com/OpenMPDK/xNVMe/blob/next/include/xnvme_spec.h

By doing so, the backend can "dispatch" based on the "pseudo-command-opcode" in a dispatch function instead of requiring adding more and more function pointers for their operation needed.

A work-in-progress example is available on PR #353 specifically here:

- https://github.com/OpenMPDK/xNVMe/pull/353/commits/0bc06ec6a530f99912a357995c16bef871f3b214

So, if it is acceptable to you, then I will wait to integrate this PR until we have done the following:

- Bumped SPDK subproject and integrated on ``next``

- Integrated PR #353 on ``next``

If you want to, I can update the PR #350 with the change needed from "function-pointer" to "pseudo-command" and rebase once these other items are taken care of.

Best,
Simon

**Comment by karlowich** [comment]
@safl To avoid blocking this, I propose that we bump SPDK to v23.01 first (#356), since it is a longer process to get to SPDK v23.09

**Comment by hmi-jeon** [comment]
Hi @safl 

Thanks for letting me know.

we confirmed the two things you mentioned.

so we will apply two things.
1. remove spdk_nvme_ctrl_get_registers patch file except for the "spdk-win" subproject, which still needs them.
2. change from "function-pointer" to "pseudo-command" after merge #353 

Thank you for helping.

**Comment by safl** [comment]
Hi @hmi-jeon,

I have not integrated these changes based on the infrastructure in xNVMe for "pseudo-commands" and NVMe-controller-handles on the PR here:
https://github.com/OpenMPDK/xNVMe/pull/386
Can you have a look to see that I have credited you properly and that the behavior is as you intended?

I will close this PR as we can move forward on PR  #386 

Thanks!

**Pull request closed without merging**
